apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        cronjob: {{ .Chart.Name }}
    spec:
      template:  
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: {{ .Values.image }}
            env:
            - name: DAYS_WARNING
              value: "{{ .Values.daysWarning }}"
          restartPolicy: "Never"
          dnsPolicy: "None"
          imagePullSecrets:
          - name: repo.name
          dnsConfig:
            nameservers:
              - 8.8.8.8
            options:
              - name: ndots
                value: "1"
            
